logging:
  level: INFO
  loggers:
    com.codingzero.saam: DEBUG

apiKey: ${API_KEY:-123456}

server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9081

mysql:
  url: ${MYSQL_URL:-localhost:3306}
  username: ${MYSQL_USERNAME:-root}
  password: ${MYSQL_PASSWORD:-"123456"}
  connectionMinPoolSize: ${MYSQL_CONNECTION_MIN_POOL_SIZE:-1}
  connectionMaxPoolSize: ${MYSQL_CONNECTION_MAX_POOL_SIZE:-5}
